### PR TITLE
Fix FC props in React 18

### PR DESCRIPTION
**Pull request by ITJesse**

### CODE REVIEW

**Comment by dvelezroman** [comment]
this is necessary for typescript repos... please merge ASAP

**Comment by alexspyr** [comment]
Please merge this. It's breaking otherwise with React 18+

**Comment by niconiahi** [comment]
should be working now on `1.4.9`. Feel free to open an issue otherwise. Also bumped all dependencies

**Comment by ITJesse** [comment]
Do you mean `1.4.19`? XD

**Pull request merged**
